Attempt to handle missing data at the starts and ends of gpuboxes.
When looking at MWA obsid 1088374448, this code currently gives this error:

ValueError: UVParameter _metric_array is not expected shape. Parameter shape is (422656, 1, 96, 4), expected shape is (430784, 1, 96, 4).

The former shape is the desired shape, but, in some way I don't understand,
pyuvdata complains that the latter shape is what is expected.